# single load balancer powered by ingress-nginx will route traffic to different HTTP backend services
# https://kubernetes.github.io/ingress-nginx/user-guide/basic-usage/
# https://kubernetes.io/docs/concepts/services-networking/ingress/
# https://stackoverflow.com/questions/72224230/error-resource-mapping-not-found-make-sure-crds-are-installed-first
#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    # kubernetes.io/ingress.class: nginx -> deprecated, use 'spec.ingressClassName' instead
    nginx.ingress.kubernetes.io/use-regex: 'true' # enable regexp for path matches

spec:
  ingressClassName: nginx
  rules: # routing rules, path based !
    - host: posts.com
      http:
        paths: # paths should be listed from the most specific ones !!
          - path: /posts/create
            pathType: Prefix # https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types
            backend:
              service:
                name: posts-srv
                port:
                  number: 4000
          - path: /posts
            pathType: Prefix
            backend:
              service:
                name: query-srv
                port:
                  number: 4200
          - path: /posts/?(.*)/comments
            pathType: ImplementationSpecific
            backend:
              service:
                name: comments-srv
                port:
                  number: 4100
          - path: /?(.*) # should be the last path listed ! we use regex to support SPA routing
            pathType: ImplementationSpecific
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
